# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b366dc9ef5b41812b069fc6b718cc218c98215195786654cda636609c8207e2dd0b3f5032cb8ef195c48c915222f47da90da14b968450f78b37e5a8991e98b4f

test:
  secret_key_base: e8ddc0af5b3f1bf20fc2a0f587c5849cfd23c40284d294fa55ab83321c9c9e91f531f97dec874f2e1f2fa86792d10b8e6684e8184fe895b8955ec5c4dd19c83a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
